In [2]:
import numpy as np
import pandas as pd

In [2]:
#合併 NMOSD & Healthy Control hugo symbol genes
nmosd_hugo=pd.read_csv("./Dataset/nmosd/mtx_nmosd/Origin_DATA/nmosd_features_ori.tsv",header=None,names=["HugoSymbol"])
control_hugo=pd.read_csv("./Dataset/Healthy_Control/mtx_control/5Healthy_Control/Healthy_Control_features.tsv",header=None,names=["HugoSymbol"])

In [6]:
nmosd_hugo

       HugoSymbol
0      AL627309.1
1      AL627309.5
2      AP006222.2
3       LINC01409
4          FAM87B
...           ...
26130  BX649601.1
26131  AL845552.2
26132  AC023310.4
26133  AL023881.1
26134  AC005529.1

[26135 rows x 1 columns]

In [8]:
control_hugo

       HugoSymbol
0           VAMP7
1           WDR44
2         C9orf16
3            LCN2
4             GSN
...           ...
24536   IGKV2D-36
24537  AC007279.2
24538  AC073878.1
24539  AL162497.1
24540  AL355474.1

[24541 rows x 1 columns]

In [13]:
hugo_merged = nmosd_hugo.merge(control_hugo, on="HugoSymbol", how="inner")
print(f'NMOSD 原始基因數:',nmosd_hugo.shape[0])
print(f'Control 原始基因數:',control_hugo.shape[0])
print(f'交集後的 Hugo Symbol genes:',hugo_merged.shape[0])

NMOSD 原始基因數: 26135
Control 原始基因數: 24541
交集後的 Hugo Symbol genes: 23763

In [10]:
hugo_merged

       HugoSymbol
0      AL627309.1
1      AL627309.5
2      AP006222.2
3       LINC01409
4          FAM87B
...           ...
23758  AC040963.1
23759   IGLV11-55
23760      FAM13C
23761      TAS2R8
23762  AC005757.1

[23763 rows x 1 columns]

In [15]:
import pandas as pd

# 讀入 mapping (兩欄：symbol, ENSG)
mapping = pd.read_csv("./Dataset/mapping_v32.csv", header=None, names=["HugoSymbol", "ENSG"])

# 合併
merged = hugo_merged.merge(mapping, on="HugoSymbol", how="left")

# 存成新 CSV
merged.to_csv("./Dataset/HUGO_with_ENSG_v32.csv", index=False)

print("Done! 輸出檔案：HUGO_with_ENSG_v32.csv")

Done! 輸出檔案：HUGO_with_ENSG_v32.csv

In [16]:
hugo_merged.shape

(23763, 1)

In [17]:
mapping.shape

(60668, 2)

In [18]:
mapping.iloc[0:5, :]

    HugoSymbol               ENSG
0      DDX11L1  ENSG00000223972.5
1       WASH7P  ENSG00000227232.5
2    MIR6859-1  ENSG00000278267.1
3  MIR1302-2HG  ENSG00000243485.5
4    MIR1302-2  ENSG00000284332.1

In [20]:
mapping_duplicates = mapping[mapping.duplicated(subset=["HugoSymbol"], keep=False)]
print(f"Mapping 中有 {mapping_duplicates.shape[0]} 個重複的 HugoSymbol")
print(mapping_duplicates.iloc[0:10, :])

Mapping 中有 1369 個重複的 HugoSymbol
    HugoSymbol               ENSG
30          U6  ENSG00000278757.1
281      Y_RNA  ENSG00000200344.1
293      Y_RNA  ENSG00000252254.1
300      Y_RNA  ENSG00000222511.2
419      Y_RNA  ENSG00000202461.1
430    SNORA70  ENSG00000252969.1
756      Y_RNA  ENSG00000201405.1
798      Y_RNA  ENSG00000239106.1
837      Y_RNA  ENSG00000207302.1
876      Y_RNA  ENSG00000252802.1

In [21]:
# 檢查是否有重複的 HugoSymbol
hugo_ENSG_df = pd.read_csv("./Dataset/HUGO_with_ENSG_v32.csv")
duplicates = hugo_ENSG_df[hugo_ENSG_df.duplicated(subset=["HugoSymbol"], keep=False)]
if not duplicates.empty:
    print(f"有重複的 HugoSymbol，共 {duplicates.shape[0]} 筆：")
    display(duplicates)
else:
    print("沒有重複的 HugoSymbol。")

有重複的 HugoSymbol，共 104 筆：

       HugoSymbol                      ENSG
1867         TBCE         ENSG00000285053.1
1868         TBCE         ENSG00000284770.2
2752     C2orf27A         ENSG00000287151.1
2753     C2orf27A        ENSG00000197927.13
3291    LINC01238         ENSG00000237940.3
...           ...                       ...
21326  AL683807.2   ENSG00000234622.6_PAR_Y
22916      WASIR1        ENSG00000185203.12
22917      WASIR1  ENSG00000185203.12_PAR_Y
22936   LINC00102         ENSG00000230542.6
22937   LINC00102   ENSG00000230542.6_PAR_Y

[104 rows x 2 columns]

In [22]:
hugo_ENSG_df.shape

(23815, 2)

In [23]:
duplicates.to_csv("./Dataset/HUGO_with_ENSG_v32(duplicated).csv", index=False)

In [30]:
print(f'Raw Hugo Symbol counts: {hugo_merged.shape[0]}')
print(f'After Mapping Ensembl ID counts: {hugo_ENSG_df["ENSG"].notna().sum()}')
print(f'missing Ensembl ID  counts: {hugo_ENSG_df["ENSG"].isna().sum()}')
print(f'Dupicated Hugo Symbol counts: {duplicates.shape[0]}')

Raw Hugo Symbol counts: 23763
After Mapping Ensembl ID counts: 23815
missing Ensembl ID  counts: 0
Dupicated Hugo Symbol counts: 104

In [26]:
hugo_ENSG_df.loc[hugo_ENSG_df["ENSG"].isna(),]

Empty DataFrame
Columns: [HugoSymbol, ENSG]
Index: []

In [27]:
hugo_ENSG_df.loc[hugo_ENSG_df["ENSG"].notna(),].to_csv("./Dataset/HUGO_with_ENSG_v32(no_missing_ENSG).csv", index=False)

In [28]:
hugo_ENSG_df.loc[hugo_ENSG_df["ENSG"].isna(),].to_csv("./Dataset/HUGO_with_ENSG_v32(missing_ENSG).csv", index=False)

### 合併gencode v32 & v44

In [3]:
ref_v32_genes = pd.read_csv("./Dataset/mapping_v32.csv",header=None,names=["HugoSymbol","ENSG"])
ref_v32_genes

        HugoSymbol               ENSG
0          DDX11L1  ENSG00000223972.5
1           WASH7P  ENSG00000227232.5
2        MIR6859-1  ENSG00000278267.1
3      MIR1302-2HG  ENSG00000243485.5
4        MIR1302-2  ENSG00000284332.1
...            ...                ...
60663   AC007325.1  ENSG00000276017.1
60664   AC007325.4  ENSG00000278817.1
60665   AC007325.2  ENSG00000277196.4
60666           U6  ENSG00000278625.1
60667           U1  ENSG00000277374.1

[60668 rows x 2 columns]

In [4]:
ref_v32_genes["ENSG"] = ref_v32_genes["ENSG"].str.split(".").str[0]
ref_v32_genes

        HugoSymbol             ENSG
0          DDX11L1  ENSG00000223972
1           WASH7P  ENSG00000227232
2        MIR6859-1  ENSG00000278267
3      MIR1302-2HG  ENSG00000243485
4        MIR1302-2  ENSG00000284332
...            ...              ...
60663   AC007325.1  ENSG00000276017
60664   AC007325.4  ENSG00000278817
60665   AC007325.2  ENSG00000277196
60666           U6  ENSG00000278625
60667           U1  ENSG00000277374

[60668 rows x 2 columns]

In [5]:
ref_v44_genes = pd.read_csv("./Dataset/features_v44.tsv",header=None,names=["ENSG","HugoSymbol","Type"],sep="\t").loc[:,["ENSG","HugoSymbol"]]
ref_v44_genes

                  ENSG       HugoSymbol
0      ENSG00000290825          DDX11L2
1      ENSG00000243485      MIR1302-2HG
2      ENSG00000237613          FAM138A
3      ENSG00000290826  ENSG00000290826
4      ENSG00000186092            OR4F5
...                ...              ...
38601  ENSG00000277836  ENSG00000277836
38602  ENSG00000278633  ENSG00000278633
38603  ENSG00000276017  ENSG00000276017
38604  ENSG00000278817  ENSG00000278817
38605  ENSG00000277196  ENSG00000277196

[38606 rows x 2 columns]

In [6]:
#Gencode v44 duplicate check
dup_v44_ENSG = ref_v44_genes[ref_v44_genes["ENSG"].duplicated(keep=False)]
dup_v44_hugo = ref_v44_genes[ref_v44_genes["HugoSymbol"].duplicated(keep=False)]

print("v44 Ensembl ID duplicates counts:",dup_v44_ENSG.shape[0])
print("v44 Ensembl ID duplicates:",dup_v44_ENSG)
print("----------------------------------------------")
print("v44 Hugo Symbol duplicates counts:",dup_v44_hugo.shape[0])
print("v44 Hugo Symbol duplicates :\n",dup_v44_hugo)

v44 Ensembl ID duplicates counts: 0
v44 Ensembl ID duplicates: Empty DataFrame
Columns: [ENSG, HugoSymbol]
Index: []
----------------------------------------------
v44 Hugo Symbol duplicates counts: 43
v44 Hugo Symbol duplicates :
                   ENSG      HugoSymbol
1918   ENSG00000288905          LSP1P5
3610   ENSG00000272342       LINC01115
3613   ENSG00000237667       LINC01115
4708   ENSG00000291150          LSP1P5
6275   ENSG00000237940       LINC01238
6280   ENSG00000261186       LINC01238
7028   ENSG00000241111    PRICKLE2-AS1
7031   ENSG00000241572    PRICKLE2-AS1
13469  ENSG00000268592      RAET1E-AS1
13471  ENSG00000223701      RAET1E-AS1
15596  ENSG00000277526       LINC03021
15597  ENSG00000254319       LINC03021
15830  ENSG00000253147       LINC03023
15831  ENSG00000254026       LINC03023
15884  ENSG00000246582    TNFRSF10A-DT
15885  ENSG00000250714    TNFRSF10A-DT
16038  ENSG00000253161       LINC01605
16040  ENSG00000253414       LINC01605
17526  ENSG00000276462       LINC03025
17601  ENSG00000234394       LINC03025
17791  ENSG00000229694       LINC00484
17792  ENSG00000235641       LINC00484
19261  ENSG00000236756      DNAJC9-AS1
19263  ENSG00000227540      DNAJC9-AS1
23091  ENSG00000258137       GPR84-AS1
23092  ENSG00000258086       GPR84-AS1
24269  ENSG00000182957         SPATA13
24270  ENSG00000228741         SPATA13
26696  ENSG00000188626         GOLGA8M
26697  ENSG00000261480         GOLGA8M
26727  ENSG00000289083       LINC02256
26751  ENSG00000261064       LINC02256
27933  ENSG00000290824        DDX11L16
27934  ENSG00000290355        DDX11L16
28400  ENSG00000183889          NPIPA9
28415  ENSG00000233024          NPIPA9
34855  ENSG00000125863            MKKS
34856  ENSG00000285508            MKKS
34857  ENSG00000285723            MKKS
36883  ENSG00000243902           ELFN2
36884  ENSG00000166897           ELFN2
37932  ENSG00000271147  ARMCX5-GPRASP2
37937  ENSG00000286237  ARMCX5-GPRASP2

In [7]:
#Gencode v32 duplicate check
dup_v32 = ref_v32_genes[ref_v32_genes["ENSG"].duplicated(keep=False)]
print("V32 duplicates:\n", dup_v32)

V32 duplicates:
        HugoSymbol             ENSG
57582  AL954722.1  ENSG00000228572
57583      PLCXD1  ENSG00000182378
57584      GTPBP6  ENSG00000178605
57585   LINC00685  ENSG00000226179
57586     PPP2R3B  ENSG00000167393
...           ...              ...
60567        IL9R  ENSG00000124334
60568  AJ271736.1  ENSG00000270726
60569      WASIR1  ENSG00000185203
60570      WASH6P  ENSG00000182484
60571    DDX11L16  ENSG00000227159

[90 rows x 2 columns]

In [8]:
#NMOSD features
nmosd_hugo=pd.read_csv("./Dataset/nmosd/mtx_nmosd/Origin_DATA/nmosd_features_ori.tsv",header=None,names=["HugoSymbol"]) 
nmosd_v32_genes=nmosd_hugo.merge(ref_v32_genes,on="HugoSymbol",how="left")
print("NMOSD original Hugo Symbol counts:",nmosd_hugo.shape[0])
print("NMOSD mapping to genecode v32 gene counts:",nmosd_v32_genes.shape[0])
nmosd_v32_genes

NMOSD original Hugo Symbol counts: 26135
NMOSD mapping to genecode v32 gene counts: 26188

       HugoSymbol             ENSG
0      AL627309.1  ENSG00000238009
1      AL627309.5  ENSG00000241860
2      AP006222.2  ENSG00000286448
3       LINC01409  ENSG00000237491
4          FAM87B  ENSG00000177757
...           ...              ...
26183  BX649601.1  ENSG00000273473
26184  AL845552.2  ENSG00000259031
26185  AC023310.4  ENSG00000278626
26186  AL023881.1  ENSG00000276984
26187  AC005529.1  ENSG00000234208

[26188 rows x 2 columns]

In [9]:
nmosd_v32_genes.to_csv("./Dataset/nmosd_v32_HUGO_map_ENSG.csv",index=False)

In [9]:
# NMOSD_v32 和 Control_v44 features merge
merged_genes_nmosd_control=ref_v44_genes.merge(nmosd_v32_genes,on="ENSG",how="inner",suffixes=('_v44', '_v32'))
merged_genes_nmosd_control

                  ENSG   HugoSymbol_v44 HugoSymbol_v32
0      ENSG00000238009  ENSG00000238009     AL627309.1
1      ENSG00000239945  ENSG00000239945     AL627309.3
2      ENSG00000241860  ENSG00000241860     AL627309.5
3      ENSG00000286448  ENSG00000286448     AP006222.2
4      ENSG00000237491        LINC01409      LINC01409
...                ...              ...            ...
25944  ENSG00000275869  ENSG00000275869     AC136612.1
25945  ENSG00000277836  ENSG00000277836     AC141272.1
25946  ENSG00000276017  ENSG00000276017     AC007325.1
25947  ENSG00000278817  ENSG00000278817     AC007325.4
25948  ENSG00000277196  ENSG00000277196     AC007325.2

[25949 rows x 3 columns]

In [10]:
# 篩選  NMOSD_v32 和 Control_v44 不相同的列
diff_genes_nmosd_control =merged_genes_nmosd_control[merged_genes_nmosd_control["HugoSymbol_v44"] != merged_genes_nmosd_control["HugoSymbol_v32"]]

print(diff_genes_nmosd_control.shape)
print(diff_genes_nmosd_control)

(7158, 3)
                  ENSG   HugoSymbol_v44 HugoSymbol_v32
0      ENSG00000238009  ENSG00000238009     AL627309.1
1      ENSG00000239945  ENSG00000239945     AL627309.3
2      ENSG00000241860  ENSG00000241860     AL627309.5
3      ENSG00000286448  ENSG00000286448     AP006222.2
9      ENSG00000272438  ENSG00000272438     AL645608.6
...                ...              ...            ...
25944  ENSG00000275869  ENSG00000275869     AC136612.1
25945  ENSG00000277836  ENSG00000277836     AC141272.1
25946  ENSG00000276017  ENSG00000276017     AC007325.1
25947  ENSG00000278817  ENSG00000278817     AC007325.4
25948  ENSG00000277196  ENSG00000277196     AC007325.2

[7158 rows x 3 columns]

In [11]:
# Check merge_df "Nan"
print("Merge nmosd_control ref genes 'Nan counts':\n",merged_genes_nmosd_control.isna().sum())

Merge nmosd_control ref genes 'Nan counts':
 ENSG              0
HugoSymbol_v44    0
HugoSymbol_v32    0
dtype: int64

In [11]:
diff_genes_nmosd_control.to_csv("./Dataset/ref_nmosd_control_different_genes.csv", index=False)

In [12]:
merged_genes_nmosd_control

                  ENSG   HugoSymbol_v44 HugoSymbol_v32
0      ENSG00000238009  ENSG00000238009     AL627309.1
1      ENSG00000239945  ENSG00000239945     AL627309.3
2      ENSG00000241860  ENSG00000241860     AL627309.5
3      ENSG00000286448  ENSG00000286448     AP006222.2
4      ENSG00000237491        LINC01409      LINC01409
...                ...              ...            ...
25944  ENSG00000275869  ENSG00000275869     AC136612.1
25945  ENSG00000277836  ENSG00000277836     AC141272.1
25946  ENSG00000276017  ENSG00000276017     AC007325.1
25947  ENSG00000278817  ENSG00000278817     AC007325.4
25948  ENSG00000277196  ENSG00000277196     AC007325.2

[25949 rows x 3 columns]

In [15]:
#ENSG 重複 ->取第一筆
merge_dup_ENSG=merged_genes_nmosd_control[merged_genes_nmosd_control["ENSG"].duplicated(keep=False)]
print(f'Merge duplicated ENSG counts:',merge_dup_ENSG.shape[0])
merged_unique_ENSG = merged_genes_nmosd_control.drop_duplicates(subset="ENSG", keep="first")
merged_unique_ENSG= merged_unique_ENSG.loc[:,["ENSG","HugoSymbol_v44"]]

Merge duplicated ENSG counts: 56

In [17]:
merged_unique_ENSG

                  ENSG   HugoSymbol_v44
0      ENSG00000238009  ENSG00000238009
1      ENSG00000239945  ENSG00000239945
2      ENSG00000241860  ENSG00000241860
3      ENSG00000286448  ENSG00000286448
4      ENSG00000237491        LINC01409
...                ...              ...
25944  ENSG00000275869  ENSG00000275869
25945  ENSG00000277836  ENSG00000277836
25946  ENSG00000276017  ENSG00000276017
25947  ENSG00000278817  ENSG00000278817
25948  ENSG00000277196  ENSG00000277196

[25921 rows x 2 columns]

In [19]:
merged_unique_ENSG.rename(columns={"HugoSymbol_v44":"HugoSymbol_merged"},inplace=True)

In [20]:
merged_hugo_dup = merged_unique_ENSG[merged_unique_ENSG["HugoSymbol_merged"].duplicated(keep=False)]
print(f'Merged duplicated Hugo Symbol counts:',merged_hugo_dup.shape[0])
merged_hugo_dup

Merged duplicated Hugo Symbol counts: 20

                  ENSG HugoSymbol_merged
4297   ENSG00000237940         LINC01238
4299   ENSG00000261186         LINC01238
10379  ENSG00000277526         LINC03021
10380  ENSG00000254319         LINC03021
10533  ENSG00000246582      TNFRSF10A-DT
10534  ENSG00000250714      TNFRSF10A-DT
10626  ENSG00000253161         LINC01605
10627  ENSG00000253414         LINC01605
11721  ENSG00000229694         LINC00484
11722  ENSG00000235641         LINC00484
12749  ENSG00000236756        DNAJC9-AS1
12751  ENSG00000227540        DNAJC9-AS1
15324  ENSG00000258137         GPR84-AS1
15325  ENSG00000258086         GPR84-AS1
17628  ENSG00000188626           GOLGA8M
17629  ENSG00000261480           GOLGA8M
18841  ENSG00000183889            NPIPA9
18848  ENSG00000233024            NPIPA9
25589  ENSG00000271147    ARMCX5-GPRASP2
25594  ENSG00000286237    ARMCX5-GPRASP2

In [22]:
print(f'NMOSD origin ENSG counts:',nmosd_hugo.shape[0])
print(f'Control origin ENSG counts:',ref_v44_genes.shape[0])
print(f'NMOSD_v32 with Control_v44 merged ENSG counts:',merged_unique_ENSG.shape[0])
print(f'Merged duplicated Hugo Symbol counts:',merged_hugo_dup.shape[0])

NMOSD origin ENSG counts: 26135
Control origin ENSG counts: 38606
NMOSD_v32 with Control_v44 merged ENSG counts: 25921
Merged duplicated Hugo Symbol counts: 20

In [ ]:
#merged_unique_ENSG.to_csv("./Dataset/NMOSD_v32_Control_v44_merged_genes.csv", index=False)